### PR TITLE
Boost 1.86 compatibility

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Fix:

```
In file included from $SRC_DIR/gazebo/common/BVHLoader.cc:27:
$SRC_DIR/gazebo/common/CommonIface.hh: In function 'std::string gazebo::common::get_sha1(const T&)':
$SRC_DIR/gazebo/common/CommonIface.hh:244:21: error: cannot convert 'unsigned int [5]' to 'unsigned char (&)[20]'
  244 |     sha1.get_digest(hash);
      |                     ^~~~
      |                     |
      |                     unsigned int [5]
```

### CODE REVIEW

**Review by scpeters — APPROVED** [review]

**Comment by scpeters** [comment]
thanks for the quick fix! it looks like it works with the version of boost in 20.04 as well. I'll merge after CI finishes
