### PR TITLE
Fix build with boost 1.85.0

### LINKED ISSUE #3385: gazebo11.14.0 fails to build against boost 1.85.0
## Environment
* OS Version: macOS: 12.6.6-x86_64 
* Source or binary build? source build of `gazebo11` branch as of 291ab64ce54b7dfaa89422686c9d38e2bc16659c
  
  

## Description
* Expected behavior: gazebo11 should compile
* Actual behavior: it fails to compile since boost 1.85.0 was merged into homebrew-core in https://github.com/Homebrew/homebrew-core/pull/169237

## Steps to reproduce

1. Build from source on macOS with boost 1.85.0 from homebrew or run https://build.osrfoundation.org/job/gazebo-ci-gazebo11-homebrew-amd64
2.
3.

## Output

[Build Status](https://build.osrfoundation.org/job/gazebo-ci-gazebo11-homebrew-amd64/205/) https://build.osrfoundation.org/job/gazebo-ci-gazebo11-homebrew-amd64/205/

~~~
gazebo/common/Console.cc:224:34: error: no member named 'branch_path' in 'boost::filesystem::path'
    this->logDirectory = logPath.branch_path().string();
                         ~~~~~~~ ^
1 error generated.
~~~

The `branch_path` method had been deprecated and is now removed:

~~~
'branch_path' is deprecated: Use path::parent_path() instead
~~~

https://build.osrfoundation.org/job/gazebo-ci-gazebo11-homebrew-amd64/204/clang/fileName.1462497174/

### PR DESCRIPTION
**Pull request by scpeters**
# 🦟 Bug fix

Fixes #3385.

## Summary

The `branch_path` API was [deprecated](https://github.com/boostorg/filesystem/blob/boost-1.71.0/include/boost/filesystem/path.hpp#L589) and has been removed in boost 1.85.0. This uses the recommended replacement method `parent_path`.

## Checklist
- [X] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by scpeters** [comment]
this isn't quite enough; it's still failing

**Comment by scpeters** [comment]
looks like `basename` and `extension` were deprecated / removed as well

~~~
/Users/scpeters/ws/gazebo/src/gazebo/gazebo/util/LogPlay.cc:417:29: error: no member named 'basename' in namespace 'boost::filesystem'
  return boost::filesystem::basename(this->dataPtr->filename) +
         ~~~~~~~~~~~~~~~~~~~^
/Users/scpeters/ws/gazebo/src/gazebo/gazebo/util/LogPlay.cc:418:24: error: no member named 'extension' in namespace 'boost::filesystem'
    boost::filesystem::extension(this->dataPtr->filename);
    ~~~~~~~~~~~~~~~~~~~^
2 errors generated.
~~~

https://github.com/boostorg/filesystem/blob/boost-1.84.0/include/boost/filesystem/convenience.hpp#L28-L38

**Comment by scpeters** [comment]
> looks like `basename` and `extension` were deprecated / removed as well
> 
> ```
> /Users/scpeters/ws/gazebo/src/gazebo/gazebo/util/LogPlay.cc:417:29: error: no member named 'basename' in namespace 'boost::filesystem'
>   return boost::filesystem::basename(this->dataPtr->filename) +
>          ~~~~~~~~~~~~~~~~~~~^
> /Users/scpeters/ws/gazebo/src/gazebo/gazebo/util/LogPlay.cc:418:24: error: no member named 'extension' in namespace 'boost::filesystem'
>     boost::filesystem::extension(this->dataPtr->filename);
>     ~~~~~~~~~~~~~~~~~~~^
> 2 errors generated.
> ```
> 
> https://github.com/boostorg/filesystem/blob/boost-1.84.0/include/boost/filesystem/convenience.hpp#L28-L38

fix in https://github.com/gazebosim/gazebo-classic/pull/3386/commits/27c2277a2376f9d82755e975ae8b564d9d6ca6ed

**Review by traversaro — APPROVED** [review]
