### ISSUE TITLE
AUTOMOC  problems with CMake  3.17-rc3

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#2702]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/2702)) by Silvio Traversaro (Bitbucket: [traversaro](https://bitbucket.org/%7B34f404cb-5642-4f27-a032-e04c7143d776%7D/)).**

----------------------------------------
When  compiling Gazebo  11 on  Windows with the latest CMake,  I experienced several CMake configuration warnings due to an unset new CMake policy on the automoc of  `.hh` files \([https://cmake.org/cmake/help/v3.17/policy/CMP0100.html](https://cmake.org/cmake/help/v3.17/policy/CMP0100.html)\):

```restructuredtext
CMake Warning (dev) in gazebo/gui/CMakeLists.txt:
  Policy CMP0100 is not set: Let AUTOMOC and AUTOUIC process .hh files.  Run
  "cmake --help-policy CMP0100" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  For compatibility, CMake is excluding the header file(s):

    "C:/idjl-ws/src/gazebo/gazebo/gui/Actions.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/ModelManipulator.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/AlignWidget.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/ApplyWrenchDialog.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/DataLogger.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/ViewAngleWidget.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/CloneWindow.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/Conversions.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/model/LinkInspector.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/ConfigWidget.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/viewers/ImagesView.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/Editor.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/UserCmdHistory.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/EntityMaker.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/GLWidget.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/MouseEventHandler.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/GuiEvents.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/VideoRecorder.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/GuiIface.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/InsertModelWidget.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/terrain/TerrainEditor.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/JointControlWidget.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/KeyEventHandler.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/LayersWidget.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/LightMaker.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/LogPlayWidget.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/MainWindow.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/ModelAlign.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/ModelListWidget.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/ModelMaker.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/viewers/ImageView.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/ModelRightMenu.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/ModelSnap.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/RenderWidget.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/SaveEntityDialog.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/GrabberHandle.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/SpaceNav.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/model/ModelEditor.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/SplashScreen.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/TimePanel.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/BuildingModelManip.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/TimeWidget.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/ToolsWidget.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/TopicSelector.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/TopToolbar.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/BuildingEditor.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/EditorItem.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/viewers/ImageFrame.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/viewers/LaserView.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/viewers/TopicView.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/viewers/TextView.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/viewers/ViewFactory.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/terrain/TerrainEditorPalette.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/BaseInspectorDialog.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/BuildingEditorEvents.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/BuildingEditorPalette.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/BuildingEditorWidget.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/BuildingMaker.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/DoorItem.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/EditorView.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/FloorItem.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/GridLines.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/ImportImageDialog.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/ImportImageView.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/LevelInspectorDialog.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/LevelWidget.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/plot/VariablePill.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/MeasureItem.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/RectItem.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/RotateHandle.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/plot/PlotWindow.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/ScaleWidget.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/SegmentItem.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/StairsInspectorDialog.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/StairsItem.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/WallInspectorDialog.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/WallSegmentItem.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/WindowDoorInspectorDialog.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/building/WindowItem.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/model/CollisionConfig.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/model/EditorMaterialSwitcher.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/model/ExtrudeDialog.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/model/ImportDialog.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/model/JointCreationDialog.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/model/JointInspector.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/model/JointMaker.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/model/LinkConfig.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/model/MEUserCmdManager.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/model/ModelCreator.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/model/ModelData.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/model/ModelEditorEvents.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/model/ModelEditorPalette.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/model/ModelPluginInspector.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/model/ModelTreeWidget.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/model/VisualConfig.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/plot/EditableLabel.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/plot/ExportDialog.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/plot/IncrementalPlot.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/plot/IntrospectionCurveHandler.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/plot/Palette.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/plot/PlotCanvas.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/plot/PlotCurve.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/plot/PlotManager.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/plot/PlotTracker.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/plot/TopicCurveHandler.hh"
    "C:/idjl-ws/src/gazebo/gazebo/gui/plot/VariablePillContainer.hh"

  from processing by AUTOMOC.  If any of the files should be processed, set
  CMP0100 to NEW.  If any of the files should not be processed, explicitly
  exclude them by setting the source file property SKIP_AUTOMOC:

    set_property(SOURCE file.hh PROPERTY SKIP_AUTOMOC ON)

This warning is for project developers.  Use -Wno-dev to suppress it.
```

 and linking problem as apparently the automoc as not executed:

‌

```
  Automatic MOC for target gazebo_gui
     Creating library C:/idjl-ws/build/Gazebo/gazebo/gui/Release/gazebo_gui.lib and object C:/idjl-ws/build/Gazebo/gazebo/gui/Release/gazebo_gui.exp
ModelEditor.obj : error LNK2001: unresolved external symbol "public: virtual struct QMetaObject const * __cdecl gazebo::gui::DeleteAction::metaObject(void)const " (?metaObject@DeleteAction@gui@gazebo@@UEBAPEBUQMetaObject@@XZ) [C:\idjl-ws\build\Gazebo\gazebo\gui\gazebo_gui.vcxproj]
ModelEditorPalette.obj : error LNK2001: unresolved external symbol "public: virtual struct QMetaObject const * __cdecl gazebo::gui::DeleteAction::metaObject(void)const " (?metaObject@DeleteAction@gui@gazebo@@UEBAPEBUQMetaObject@@XZ) [C:\idjl-ws\build\Gazebo\gazebo\gui\gazebo_gui.vcxproj]
TerrainEditor.obj : error LNK2001: unresolved external symbol "public: virtual struct QMetaObject const * __cdecl gazebo::gui::DeleteAction::metaObject(void)const " (?metaObject@DeleteAction@gui@gazebo@@UEBAPEBUQMetaObject@@XZ) [C:\idjl-ws\build\Gazebo\gazebo\gui\gazebo_gui.vcxproj]
BuildingEditor.obj : error LNK2001: unresolved external symbol "public: virtual struct QMetaObject const * __cdecl gazebo::gui::DeleteAction::metaObject(void)const " (?metaObject@DeleteAction@gui@gazebo@@UEBAPEBUQMetaObject@@XZ) [C:\idjl-ws\build\Gazebo\gazebo\gui\gazebo_gui.vcxproj]
MEUserCmdManager.obj : error LNK2001: unresolved external symbol "public: virtual struct QMetaObject const * __cdecl gazebo::gui::DeleteAction::metaObject(void)const " (?metaObject@DeleteAction@gui@gazebo@@UEBAPEBUQMetaObject@@XZ) [C:\idjl-ws\build\Gazebo\gazebo\gui\gazebo_gui.vcxproj]
ModelCreator.obj : error LNK2001: unresolved external symbol "public: virtual struct QMetaObject const * __cdecl gazebo::gui::DeleteAction::metaObject(void)const " (?metaObject@DeleteAction@gui@gazebo@@UEBAPEBUQMetaObject@@XZ) [C:\idjl-ws\build\Gazebo\gazebo\gui\gazebo_gui.vcxproj]
TimeWidget.obj : error LNK2001: unresolved external symbol "public: virtual struct QMetaObject const * __cdecl gazebo::gui::DeleteAction::metaObject(void)const " (?metaObject@DeleteAction@gui@gazebo@@UEBAPEBUQMetaObject@@XZ) [C:\idjl-ws\build\Gazebo\gazebo\gui\gazebo_gui.vcxproj]
TopToolbar.obj : error LNK2001: unresolved external symbol "public: virtual struct QMetaObject const * __cdecl gazebo::gui::DeleteAction::metaObject(void)const " (?metaObject@DeleteAction@gui@gazebo@@UEBAPEBUQMetaObject@@XZ) [C:\idjl-ws\build\Gazebo\gazebo\gui\gazebo_gui.vcxproj]
UserCmdHistory.obj : error LNK2001: unresolved external symbol "public: virtual struct QMetaObject const * __cdecl gazebo::gui::DeleteAction::metaObject(void)const " (?metaObject@DeleteAction@gui@gazebo@@UEBAPEBUQMetaObject@@XZ) [C:\idjl-ws\build\Gazebo\gazebo\gui\gazebo_gui.vcxproj]
ViewAngleWidget.obj : error LNK2001: unresolved external symbol "public: virtual struct QMetaObject const * __cdecl gazebo::gui::DeleteAction::metaObject(void)const " (?metaObject@DeleteAction@gui@gazebo@@UEBAPEBUQMetaObject@@XZ) [C:\idjl-ws\build\Gazebo\gazebo\gui\gazebo_gui.vcxproj]
MainWindow.obj : error LNK2001: unresolved external symbol "public: virtual struct QMetaObject const * __cdecl gazebo::gui::DeleteAction::metaObject(void)const " (?metaObject@DeleteAction@gui@gazebo@@UEBAPEBUQMetaObject@@XZ) [C:\idjl-ws\build\Gazebo\gazebo\gui\gazebo_gui.vcxproj]
ModelRightMenu.obj : error LNK2001: unresolved external symbol "public: virtual struct QMetaObject const * __cdecl gazebo::gui::DeleteAction::metaObject(void)const " (?metaObject@DeleteAction@gui@gazebo@@UEBAPEBUQMetaObject@@XZ) [C:\idjl-ws\build\Gazebo\gazebo\gui\gazebo_gui.vcxproj]
RenderWidget.obj : error LNK2001: unresolved external symbol "public: virtual struct QMetaObject const * __cdecl gazebo::gui::DeleteAction::metaObject(void)const " (?metaObject@DeleteAction@gui@gazebo@@UEBAPEBUQMetaObject@@XZ) [C:\idjl-ws\build\Gazebo\gazebo\gui\gazebo_gui.vcxproj]
TimePanel.obj : error LNK2001: unresolved external symbol "public: virtual struct QMetaObject const * __cdecl gazebo::gui::DeleteAction::metaObject(void)const " (?metaObject@DeleteAction@gui@gazebo@@UEBAPEBUQMetaObject@@XZ) [C:\idjl-ws\build\Gazebo\gazebo\gui\gazebo_gui.vcxproj]
Actions.obj : error LNK2001: unresolved external symbol "public: virtual struct QMetaObject const * __cdecl gazebo::gui::DeleteAction::metaObject(void)const " (?metaObject@DeleteAction@gui@gazebo@@UEBAPEBUQMetaObject@@XZ) [C:\idjl-ws\build\Gazebo\gazebo\gui\gazebo_gui.vcxproj]
ApplyWrenchDialog.obj : error LNK2001: unresolved external symbol "public: virtual struct QMetaObject const * __cdecl gazebo::gui::DeleteAction::metaObject(void)const " (?metaObject@DeleteAction@gui@gazebo@@UEBAPEBUQMetaObject@@XZ) [C:\idjl-ws\build\Gazebo\gazebo\gui\gazebo_gui.vcxproj]
GLWidget.obj : error LNK2001: unresolved external symbol "public: virtual struct QMetaObject const * __cdecl gazebo::gui::DeleteAction::metaObject(void)const " (?metaObject@DeleteAction@gui@gazebo@@UEBAPEBUQMetaObject@@XZ) [C:\idjl-ws\build\Gazebo\gazebo\gui\gazebo_gui.vcxproj]
LogPlayWidget.obj : error LNK2001: unresolved external symbol "public: virtual struct QMetaObject const * __cdecl gazebo::gui::DeleteAction::metaObject(void)const " (?metaObject@DeleteAction@gui@gazebo@@UEBAPEBUQMetaObject@@XZ) [C:\idjl-ws\build\Gazebo\gazebo\gui\gazebo_gui.vcxproj]
ModelEditor.obj : error LNK2001: unresolved external symbol "public: virtual void * __cdecl gazebo::gui::DeleteAction::qt_metacast(char const *)" (?qt_metacast@DeleteAction@gui@gazebo@@UEAAPEAXPEBD@Z) [C:\idjl-ws\build\Gazebo\gazebo\gui\gazebo_gui.vcxproj]
```

‌

I just added the first instances of  the error to  avoid  making the issue unreadable. In theory the default OLD policy value  should provide backward compatibility, but instead in this case the `OLD`  setting of the policy is  not working, while  explicitly setting the `NEW` setting solves both problems. 

‌

**Comment by traversaro** [comment]
This problem has been fixed in https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/pull-requests/3201/page/1, so I think that this issue can be closed. However, under some conditions it is possible that the build with CMake 3.16 fails as well, but it would  not be a Gazebo issue, see https://gitlab.kitware.com/cmake/cmake/-/issues/20598 .
